### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by memes** [memes/terraform-google-secret-manager#12]
- [x] Customer keys for secrets (root module) PR #10 
- [x] Customer keys for secrets (random module) PR #11
- [x] Update CHANGELOG.md
- [x] Add examples for using customer keys with secrets
- [x] Update pre-commit/terraform docs/etc. PR #20
- [x] kitchen-terraform harness PR #21
- [x] Fix user-managed replication without CMEK PR #22
